config/routes.rb
Rails.application.routes.draw do

resources :ministries
resources :volunteers
resources :missions
  
  get '/' => 'home#show'

  get 'home/sign_up'

  get 'home/login'

  post 'home/login' => 'home#create'

  post 'missions/:id/volunteers' => 'missions#add_vol'

  post 'missions/:id/ministries' => 'missions#add_min'

 

  post '/ministries' => 'ministries#create'

end

app/models/ministry.rb
class Ministry < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :volunteers
  has_many :mission_assignments
  has_many :missions, through: :mission_assignments
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  has_secure_password

end

app/models/mission.rb
class Mission < ActiveRecord::Base
	
	
	has_many :mission_assignments
	has_many :volunteers, through: :mission_assignments
	has_many :ministries, through: :mission_assignments
end

app/models/mission_assignment.rb
class MissionAssignment < ActiveRecord::Base
	belongs_to :mission
	belongs_to :volunteer
	belongs_to :ministry
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :ministry
  has_many :missions_assignments
  has_many :missions, through: :missions_assignments
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  has_secure_password

 def self.search(search)

 	if search
 		where('name LIKE ?', "%#{search}")
 	else
 		all
 	end

 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end

	
	def show

	end

	def sign_up

	end


	def create 
	  	@volunteer = Volunteer.find_by(email: params[:email])
	  	@ministry = Ministry.find_by(email: params[:email])

	  	if @volunteer && @volunteer.authenticate(params[:password])
	  		session[:volunteer_id] = @volunteer.id
	  		redirect_to '/volunteers/'
	  	elsif @ministry && @ministry.authenticate(params[:password])
	  		session[:ministry_id] = @ministry.id
	  		redirect_to '/ministries/'
	  	else
	  		flash[:alert] = "Login Failed"
			redirect_to '/home/login'
		end
	end 



end

app/controllers/ministries_controller.rb
class MinistriesController < ApplicationController
  
  def index
    @ministry = Ministry.find_by(id: session[:ministry_id])
  end

  def new
     @ministry = Ministry.new
  end

  def create
        @ministry = Ministry.new(ministry_params)

    if @ministry.save
      redirect_to ministry_path(@ministry)
    else
      redirect_to '/home/sign_up'
    end
  end
  

  def destroy
    session.clear

    redirect_to '/'
  end

  def edit
  end

  def show
    @ministry = Ministry.find(params[:id])
  end

def ministry_params
    params.require(:ministry).permit(:name, :address, :phone, :email, :password)
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def index
    @missions = Mission.all
  end


  def new
    @missions = Mission.new
    

  end

  def create
      @missions = Mission.new(mission_params)

    if @missions.save
      redirect_to mission_path(@missions)
    else
      render :new   
    end
  end

  def destroy
  end

  def edit
    @missions = Mission.find(params[:id])

  end

  def update
    @missions = Mission.find(params[:id])
    if @missions.update(mission_params)
    flash[:notice] = 'Mission was successfully updated.' 
    redirect_to mission_path

  else 
    render "edit"

  end 
  end


  def add_vol
    @missions = Mission.find(params[:id])
     @volunteer = Volunteer.find_by(id: session[:volunteer_id])
     @missions.volunteers.push(@volunteer)
  
   
     redirect_to mission_path

  end

  def add_min
  @missions = Mission.find(params[:id])
  @ministry = Ministry.find_by(id: session[:ministry_id])
  @missions.ministries.push(@ministry)
  
   
     redirect_to mission_path
  end


  def show
     @missions = Mission.find(params[:id])
     @volunteer = Volunteer.find_by(id: session[:volunteer_id])
     @ministry = Ministry.find_by(id: session[:ministry_id])

  end

  private
  def mission_params

    params.require(:mission).permit(:name, :location, :description )

  end

end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  def index
   @volunteer = Volunteer.find_by(id: session[:volunteer_id])
   # @volunteers = Volunteer.search(params[:search])
   render :show
  end


  def new
    @volunteer = Volunteer.new
  end

  def create
      @volunteer = Volunteer.new(volunteer_params)

    if @volunteer.save

      redirect_to volunteer_path(@volunteer)
    else
       p @volunteer.errors.full_messages
      redirect_to '/home/sign_up'
    end
  end

  def destroy
    session.clear

    redirect_to '/'
  end

  def edit
  end

  def show
    @volunteer = Volunteer.find(params[:id])
  end

  private

  def volunteer_params
    params.require(:volunteer).permit(:name, :address, :email, :password, :phone )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ministries_helper.rb
module MinistriesHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/home/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Ministry Missions</title>
</head>
<body>
<p>Log In</p>
<p>New User Account</p>
</body>
</html>

app/views/home/login.html.erb
<div class="row">  
      <img class="pic1" src="/assets/church_pic.jpeg" alt="Jesus Bible">
      
   </div>
	

<form class="form1" accept-charset="UTF-8" action="/home/login" method="POST">

    <h1 style="color: black;">Login</h1>

    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="InputEmail" name="email" placeholder="Email">
 
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="InputPassword" name="password" placeholder="Password">
  </div>
 
  <input type="hidden" name="authenticity_token"
      value="<%= form_authenticity_token %>">

  <button type="submit" class="btn btn-default" id="button1">Login</button>

</form>

app/views/home/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
       <p>MissionConnect</p>
      </a>
       
    </div>
    <button class="btn bt-1 navbar-btn pull-right" onclick="location.href='home/sign_up';">Sign Up</button>
    <button class="btn bt-1 navbar-btn pull-right" onclick="location.href='home/login';">Log In</button>
    </div>

  
</nav>


   <div class="row">
      <img class="pic1" src="/assets/Jesus_bible.jpeg" alt="Jesus Bible">
      <p class="text_home tlt">Connecting together to reach Christ's Mission</p>
   </div>

app/views/home/sign_up.html.erb
<!-- 
<img class="pic2" src="/assets/Jesus_cross_mountain.jpeg" alt="Jesus Bible"> -->

<div class="row">




<form class="form1" accept-charset="UTF-8" action="/" method="post">

<h1>Sign Up</h1>

  <div class="form-group">
  <label for="exampleInputEmail1">Name </label>
    <input type="text" class="form-control" id="InputName" name="email" placeholder="Name">
  </div>

	<div class="form-group">

    <label for="exampleInputEmail1">Address</label>
    <input type="text" class="form-control" id="InputAddress" name="address" placeholder="Address">
  </div>
  <div class="form-group">

    <label for="exampleInputEmail1">Phone</label>
    <input type="text" class="form-control" id="InputPhone" name="Phone" placeholder="Phone Number">
  </div>
  	<div class="form-group">

    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="InputEmail" name="Email" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="InputPassword" name="password" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="InputPasswordConfirmation" name="password_confirmation" placeholder="Password again">
  </div>
 <!--  <div class="form-group">
    <label for="PictureInput">Select Picture</label>
    <input type="file" id="InputPicture">
    <p class="help-block">Profile Type</p>
  </div> -->
  <div class="radio1">
    <label>
    <input type="radio" name="radio" id="radio_ministry" value="Ministry">
    Ministry
  </label>
</div>
 
  <div class="radio1">
    <label>
    <input type="radio" name="radio" id="radio_volunteer" value="Volunteer">
    Volunteer
  </label>
  <input type="hidden" name="authenticity_token"
      value="<%= form_authenticity_token %>">
</div>
  <button type="submit" class="btn btn-default" id="button1">Submit</button>

</form>
</div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Church</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   
</head>
<body class="c-<%= controller_name %> a-<%= action_name %>">
<p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

</nav>
<%= yield %>

</body>
</html>

app/views/ministries/create.html.erb
<h1>Ministries#create</h1>
<p>Find me in app/views/ministries/create.html.erb</p>

app/views/ministries/destroy.html.erb
<h1>Ministries#destroy</h1>
<p>Find me in app/views/ministries/destroy.html.erb</p>

app/views/ministries/edit.html.erb
<h1>Ministries#edit</h1>
<p>Find me in app/views/ministries/edit.html.erb</p>

app/views/ministries/index.html.erb
<title>Volunteer Profile Page</title>
</head>
<body>

<h1>Ministry Name: <%= @ministry.name %></h1>

<dl>
  <dt>
    Address
  </dt>
  <dd>
    <%= @ministry.address %>
  </dd>

  <dt>
    Email
  </dt>
  <dd>
    <%= @ministry.email %>
  </dd>

  <dt>
    Phone
  </dt>
  <dd>

  <%= link_to "Log out", "/ministries/:id", :method => :delete %>

  <p>To Create a Missions Click Here</p>
 <button onclick="location.href='/missions/new';">Missions</button>
  
  </dd>
</dl>

app/views/ministries/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Ministry New Page</title>
</head>
<body>

<h1>Ministry New Page</h1>




</body>
</html>

app/views/ministries/show.html.erb
<h1>Ministry Name: <%= @ministry.name %></h1>

<dl>
  <dt>
    Address
  </dt>
  <dd>
    <%= @ministry.address %>
  </dd>

  <dt>
    Email
  </dt>
  <dd>
    <%= @ministry.email %>
  </dd>

  <dt>
    Phone
  </dt>
  <dd>

  <%= link_to "Log out", "/ministries/:id", :method => :delete %>

  <p>To Create a Missions Click Here</p>
 <button onclick="location.href='/missions/new';">Missions</button>
  
  </dd>
</dl>

app/views/missions/create.html.erb
<h1>Missions#create</h1>
<p>Find me in app/views/missions/create.html.erb</p>

app/views/missions/destroy.html.erb
<h1>Missions#destroy</h1>
<p>Find me in app/views/missions/destroy.html.erb</p>

app/views/missions/edit.html.erb
<h1>Mission Edit Page</h1>
<h1>Mission Name: <%= @missions.name %></h1>
<h2>Mission Location: <%= @missions.location %></h2>
<h2>Mission Description: <%= @missions.description %></h2>

<%= form_for @missions do |f| %>
	<%= f.label :missions_name %>:
	<%= f.text_field :name %>

<%= f.label :missions_location %>:
<%= f.text_field :location %>

<%= f.label :missions_description %>:
<%= f.text_field :description %>

<%= f.submit %>

<% end %>

app/views/missions/index.html.erb
<h1>Mission List</h1>

<table class="table table-inverse">
  <thead>
    <tr>
      <th>#</th>
      <th>Mission Name</th>
      <th>Mission Location</th>
      <th>Mission Description</th>
      <th>Mission Link</th>
      <th>Mission Edit</th>
    </tr>
  </thead>

<% @missions.each  do |mission| %>
	 <tr>
      <td scope="row"><%=mission.id %></th>
      <td><%=mission.name %></td>
      <td><%=mission.location %></td>
      <td><%=mission.description %></td>
      <td><%=link_to"Go to this Mission", mission_path(mission)%></td>
      <td><%=link_to"Edit Link", edit_mission_path(mission)%></td>


</tr>
<% end %>
</tbody>

		
</table>

app/views/missions/new.html.erb
<nav class="container-fluid">
    <div class="navbar-header navbar-fixed-top" style="background: rgba(0, 0, 0, 0.8);">
      <a class="navbar-brand" href="#">
       <p>Mission Connect</p>
      </a>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <!-- <button class="btn navbar-btn" onclick="location.href='home/sign_up';">Sign In</button> -->
        </div>
        <div class="btn-group" role="group">
          <!-- <button class="btn navbar-btn" onclick="location.href='home/login';">Log In</button> -->
           <%= link_to "Log out", "/volunteers/:id", :method => :delete, :class => "btn navbar-btn" %>
        </div>
      </div>
    </div>


</div>

<div class="container">
    <div class="row">
    <form action="/missions" method="POST"  role="form" class="col-md-9 go-right">
      <h2>Create a New Mission</h2>
      <div class="form-group">
      <input name="mission[name]" type="text" class="form-control" required>
      <label for="Mission Name">Mission Name</label>
    </div>
    <div class="form-group">
      <input name="mission[location]" type="text" class="form-control" required>
      <label for="location">Mission Location</label>
    </div>
    <div class="form-group">
      <textarea name="mission[description]" class="form-control" required></textarea>
      <label for="description">Description</label>
    </div>
    <input type="hidden" name="authenticity_token"
      value="<%= form_authenticity_token %>">
      
<button type="submit" class="btn btn-default" id="button2">Create</button>
    </div>
    </form>
        
  </div>
</div>

app/views/missions/show.html.erb
<nav class="container-fluid">
    <div class="navbar-header navbar-fixed-top" style="background: rgba(0, 0, 0, 0.8);">
      <a class="navbar-brand" href="#">
       <p>Mission Church</p>
      </a>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <!-- <button class="btn navbar-btn" onclick="location.href='home/sign_up';">Sign In</button> -->
        </div>
        <div class="btn-group" role="group">
          <!-- <button class="btn navbar-btn" onclick="location.href='home/login';">Log In</button> -->
           <%= link_to "Log out", "/volunteers/:id", :method => :delete, :class => "btn navbar-btn" %>
        </div>
      </div>
    </div>


<h1>Mission Name: <%= @missions.name %></h1>
<h2>Mission Location: <%= @missions.location %></h2>
<h2>Mission Description: <%= @missions.description %></h2>


<button onclick="location.href='/missions';">Missions List</button>


<form action="/missions/<%= @missions.id %>/volunteers" method="POST">
<p>Volunteers Join Here</p>
	<button type="submit">Join Mission</button>
<input type="hidden" name="authenticity_token"
      value="<%= form_authenticity_token %>">
</form>

<form action="/missions/<%= @missions.id %>/ministries" method="POST">
<p>Ministries Join Here</p>
	<button type="submit">Join Mission</button>
<input type="hidden" name="authenticity_token"
      value="<%= form_authenticity_token %>">
</form>
<h3>People Already In <%=@missions.name %></h3>

<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
    </tr>
  </thead>
  <tbody>

<% @missions.volunteers.each do | volunteer | %>
	

 <tr>
      <td scope="row"><%=volunteer.id %></th>
      <td><%=volunteer.name %></td>
      <td><%=volunteer.email %></td>
      <td><%=volunteer.address %></td>

</tr>
<% end %>
</tbody>

		
</table>
	
  <table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
    </tr>
  </thead>
  <tbody>

<h3>Ministry Already In <%=@missions.name %></h3>
<% @missions.ministries.each do | ministry | %>
	
 <tr>
      <td scope="row"><%=ministry.id %></th>
      <td><%=ministry.name %></td>
      <td><%=ministry.email %></td>
      <td><%=ministry.address %></td>

</tr>
<% end %>
</tbody>

    
</table>

app/views/volunteers/create.html.erb
<h1>Volunteers#create</h1>
<p>Find me in app/views/volunteers/create.html.erb</p>

app/views/volunteers/destroy.html.erb
<h1>Volunteers#destroy</h1>
<p>Find me in app/views/volunteers/destroy.html.erb</p>

app/views/volunteers/edit.html.erb
<h1>Volunteers#edit</h1>
<p>Find me in app/views/volunteers/edit.html.erb</p>

app/views/volunteers/index.html.erb
<title>Volunteer Profile Page via Index HTML IN Volunteers</title>

<body>

<nav class="container-fluid">
    <div class="navbar-header navbar-fixed-top" style="background: rgba(0, 0, 0, 0.8);">
      <a class="navbar-brand" href="#">
       <p>Mission Connect</p>
      </a>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <!-- <button class="btn navbar-btn" onclick="location.href='home/sign_up';">Sign In</button> -->
        </div>
        <div class="btn-group" role="group">
          <!-- <button class="btn navbar-btn" onclick="location.href='home/login';">Log In</button> -->
           <%= link_to "Log out", "/volunteers/:id", :method => :delete, :class => "btn navbar-btn" %>
        </div>
      </div>
    </div>
  

  
</nav>

<div class="container">
    <div class="fb-profile">
        <img align="left" class="fb-image-lg" src="/assets/barn_1470.jpg" alt="Profile image example"/>
        <img align="left" class="fb-image-profile thumbnail" src="/assets/profile_pic1" alt="Profile image example"/>
        <div class="fb-profile-text">
          <h2>Hello: <%= @volunteer.name %></h2>
          <p> Address: <%= @volunteer.address %></p>
          <p> Email: <%= @volunteer.email %></p>
          <p> Volunteer at ABC Church </p>





        </div>
    </div>
</div>



<div class="container">



<p>To Create a Missions Click Here</p>
 <button onclick="location.href='/missions/new';">Missions</button>
  
  </dd>
</dl>

app/views/volunteers/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Volunteer New Page</title>
</head>
<body>

<h1>Volunteer New page</h1>





</body>
</html>

app/views/volunteers/show.html.erb
	<title>Volunteer Profile Page</title>
<title>Volunteer Profile Page via SHOW HTML IN Volunteers</title>



<nav class="container-fluid">
    <div class="navbar-header navbar-fixed-top" style="background: rgba(0, 0, 0, 0.8);">
      <a class="navbar-brand" href="#">
       <p>Mission Connect</p>
      </a>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <!-- <button class="btn navbar-btn" onclick="location.href='home/sign_up';">Sign In</button> -->
        </div>
        <div class="btn-group" role="group">
          <!-- <button class="btn navbar-btn" onclick="location.href='home/login';">Log In</button> -->
           <%= link_to "Log out", "/volunteers/:id", :method => :delete, :class => "btn navbar-btn" %>
        </div>
      </div>
    </div>
  

  
</nav>

<div class="container">
<div class="row">
    <div class="fb-profile">
        <img align="left" class="fb-image-lg" src="/assets/barn_1470.jpg" alt="Profile image example"/>
        <img align="left" class="fb-image-profile thumbnail" src="/assets/profile_pic1" alt="Profile image example"/>
        <div class="fb-profile-text">
          <h2>Hello: <%= @volunteer.name %></h2>
          <p> Address: <%= @volunteer.address %></p>
          <p> Email: <%= @volunteer.email %></p>
          <p> Volunteer at ABC Church </p>
         
        </div>
        

    </div>

      
</div>
</div>
<div class="row">
<div style="width: 50%; margin: 0 auto;">
    <p>To Create a Missions Click Here</p>
        <button class="btn-primary" onclick="location.href='/missions/new';">Missions</button>
  </div>

<p>To Missions Index Click Here</p>
        <button class="btn-primary" onclick="location.href='/missions';">Missions</button>
  

</div>  